version: 0.0
os: linux
files:
  - source: CodeBuild-SampleCore/build_output
    destination: /home/ec2-user/MyAspNetCoreApp
  - source: scripts/virtualhost.conf
    destination: /home/ec2-user/MyAspNetCoreApp
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root



  AfterInstall:
    - location: scripts/installapache.sh
      timeout: 500
      runas: root

    - location: scripts/restartapache.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/startapache.sh
      timeout: 300
      runas: root
